package app

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

type copilotOptions struct {
	command     string
	projectPath string
	jsonOutput  bool
	plainOutput bool
}

func runCopilot(args []string, stdout io.Writer, stderr io.Writer) int {
	if len(args) == 0 {
		_, _ = fmt.Fprintln(stderr, "usage: ai-skill copilot <start> [flags]")
		return ExitInvalidUsage
	}
	opts := copilotOptions{command: args[0]}
	if opts.command != "start" {
		_, _ = fmt.Fprintf(stderr, "unsupported copilot command: %s\n", opts.command)
		return ExitInvalidUsage
	}

	fs := newFlagSet("copilot "+opts.command, stderr)
	fs.StringVar(&opts.projectPath, "project", ".", "target project directory")
	fs.BoolVar(&opts.jsonOutput, "json", false, "write machine-readable JSON output")
	fs.BoolVar(&opts.plainOutput, "plain", false, "write human-readable output")
	if err := fs.Parse(args[1:]); err != nil {
		return ExitInvalidUsage
	}
	if opts.jsonOutput && opts.plainOutput {
		_, _ = fmt.Fprintln(stderr, "--json and --plain are mutually exclusive")
		return ExitInvalidUsage
	}

	result := buildCopilotStartResult(opts)
	if opts.jsonOutput {
		if err := writeJSON(stdout, result); err != nil {
			_, _ = fmt.Fprintf(stderr, "write output: %v\n", err)
			return ExitGeneralFailure
		}
		return result.ExitCode
	}
	if err := writeCopilotStartPlain(stdout, result); err != nil {
		_, _ = fmt.Fprintf(stderr, "write output: %v\n", err)
		return ExitGeneralFailure
	}
	return result.ExitCode
}

func buildCopilotStartResult(opts copilotOptions) Result {
	result := Result{
		Command:        "copilot start",
		Mode:           "guided_start",
		Status:         "success",
		ExitCode:       ExitSuccess,
		Checks:         []Check{},
		PlannedActions: []string{},
		Mutations:      []string{},
		Results:        []QueryResult{},
	}
	project, projectCheck := resolveTargetProject(opts.projectPath)
	result.Checks = append(result.Checks, projectCheck)
	if projectCheck.Status != "ok" {
		result.Status = "blocked"
		result.ExitCode = ExitInvalidUsage
		result.Error = &CommandError{Code: "invalid_project", Message: projectCheck.Message, Remediation: "Pass --project with an existing project directory."}
		return result
	}
	repoHint := copilotProjectRepoHint(project)
	result.Checks = append(result.Checks, repoHint)
	prompt := copilotBootstrapPrompt(copilotProjectDisplay(project), repoHint.Message)
	result.PlannedActions = append(result.PlannedActions,
		"paste the generated bootstrap prompt as the first message in a new Copilot session",
		"ask Copilot to read the canonical bootstrap sources before any non-read action",
		"rely on repository hooks, CI, and ai-skill runtime validate as hard enforcement boundaries",
	)
	result.Results = append(result.Results, QueryResult{
		ID:          "copilot.bootstrap_prompt",
		SourcePath:  ".copilot/bootstrap-prompt.md",
		Layer:       "ai-tools",
		Type:        "startup-prompt",
		Status:      "generated",
		Priority:    "P2",
		Confidence:  "medium",
		ContextCost: "low",
		Summary:     prompt,
		MatchReason: "generated by ai-skill copilot start",
	})
	return result
}

func copilotProjectRepoHint(project string) Check {
	localEnv := filepath.Join(project, ".ai-skill", "local.env")
	content, err := os.ReadFile(localEnv)
	if err == nil {
		for _, line := range strings.Split(string(content), "\n") {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "export AI_SKILL_REPO=") {
				return Check{Name: "ai_skill_repo_hint", Status: "ok", Message: "<AI_SKILL_REPO> from .ai-skill/local.env"}
			}
		}
		return Check{Name: "ai_skill_repo_hint", Status: "warning", Message: ".ai-skill/local.env exists but does not export AI_SKILL_REPO"}
	}
	if os.Getenv("AI_SKILL_REPO") != "" {
		return Check{Name: "ai_skill_repo_hint", Status: "ok", Message: "<AI_SKILL_REPO> from environment"}
	}
	return Check{Name: "ai_skill_repo_hint", Status: "warning", Message: "set AI_SKILL_REPO or create .ai-skill/local.env before starting Copilot"}
}

func copilotProjectDisplay(project string) string {
	if rel, err := filepath.Rel(".", project); err == nil && !strings.HasPrefix(rel, "..") {
		return filepath.ToSlash(rel)
	}
	return "<PROJECT_ROOT>"
}

func copilotBootstrapPrompt(project string, repoHint string) string {
	return fmt.Sprintf(`Use Ai-skill guided startup for this Copilot session.

Project: %s
Ai-skill repo: %s

Before any non-read action:

1. Read <AI_SKILL_REPO>/CORE_BOOTSTRAP.md.
2. Read <AI_SKILL_REPO>/runtime/core-bootstrap.yaml.
3. Read <AI_SKILL_REPO>/ai-tools/agent/copilot.md.
4. Treat runtime/core-bootstrap.yaml as the canonical bootstrap contract.
5. Reply with the Bootstrap Receipt required by the canonical contract.

During the session, keep per-turn Cognitive Mode reporting and close-loop checks active. If Copilot cannot enforce a runtime gate directly, report the limitation and rely on repository hooks, CI, and ai-skill runtime validate as the hard enforcement boundary.`, project, repoHint)
}

func writeCopilotStartPlain(w io.Writer, result Result) error {
	if err := writePlain(w, result); err != nil {
		return err
	}
	if len(result.Results) == 0 {
		return nil
	}
	_, err := fmt.Fprintf(w, "\nPaste this as the first message in a new Copilot session:\n\n%s\n", result.Results[0].Summary)
	return err
}
